### ISSUE TITLE
I can not perform any operation on the subscribed data until it gets the new updates.

### ISSUE THREAD

**Issue by vishalwayachal** [ccorcos/meteor-any-db#12]
In case of multiple subscriptions to the same collection, if the collection changes I can not perform any operation on the subscribed data until it gets the new updates.

**Comment by ccorcos** [comment]
Yes. Any-Db subscriptions will callback with the "current" ground truth data. If you want to buffer changes and optimistically update on the client, you need to either use [any-store](https://github.com/ccorcos/meteor-any-store) or create your own solution. Client-side caching is not the concern of any-db
