### ISSUE TITLE
Where is Store collection ?

### ISSUE THREAD

**Issue by vishalwayachal** [ccorcos/meteor-any-db#14]
Where is Store collection ?
- Server memory
- Client side (minimongo)
- Server side
- Every time fetch data from neo4j

As per code show u are store data in server memory variable (pub) and when any changes done compare old and new data and return actual result.
if am i correct reply me

**Comment by ccorcos** [comment]
Data is in memory on the server in order to "diff" new data and only send changes to the client.

The data comes from whatever data source you want. Hence "any-db".

Also, see [any-store](https://github.com/ccorcos/meteor-any-store) if you're interested in client-side stuff.
