### ISSUE TITLE
R is not defined on client

### ISSUE THREAD

**Issue by reohjs** [ccorcos/meteor-any-db#2]
http://i.gyazo.com/b2e464c0e5f28bb6bc7b90412c0d5b2f.png

Solved using the following code:

```
Meteor.startup(function () {
  // Use Ramda on client via Ajax call to CDN
  $.getScript("//cdnjs.cloudflare.com/ajax/libs/ramda/0.17.0/ramda.min.js",
    function ( data, textStatus, jqxhr ) {
      console.log( "Loaded Ramda." );
    }
  )
})
```

**Comment by ccorcos** [comment]
Hmm. Should be covered here:

https://github.com/ccorcos/meteor-any-db/blob/master/package.js#L22

Was this in the example? The error seems to be coming from the meteor project, not the package.

**Comment by reohjs** [comment]
I used code from the neo4j chatroom example, yeah. Didn't find anything related to R in that folder though... should R be exported via the package?

**Comment by ccorcos** [comment]
No, probably just need to `meteor add ramda:ramda`
