### ISSUE TITLE
Fan mail (plus Redis support)

### ISSUE THREAD

**Issue by deanrad** [ccorcos/meteor-any-db#3]
I _love_ that you're working on this problem. I only have time for simple tasks right now, but as a user of redis-livedata (ugh!) I really wanted to abstract the client away from caring about which database the data came from, and I think that's what you're doing too right ? 

Is there any low-hanging fruit for Redis ?

**Comment by samcorcos** [comment]
There should be! Chet would have more information on that. We're in the middle of a major refactor for version 2. 

Sadly, until Minimongo is further generalized (which they appear to be working on) reactivity will be somewhat limited, as you will not be able to re-query the client database.

How reactive does your app need to be?

@ccorcos What are your thoughts?

**Comment by deanrad** [comment]
I have no specific thing in mind at the moment, as I can use MongoDB for most things. But one day I'll encounter a need and I know I'll check back here first thing.

**Comment by ccorcos** [comment]
soon enough. i believe MDG is working on Redis support as well. Redis is non-relational though right? Why not just use mongo?
