### ISSUE TITLE
movedBefore and changed DDP messages in the same transaction should be atomic

### ISSUE THREAD

**Issue by sunny-g** [ccorcos/meteor-any-db#6]
If a document has a property changed that used to compute it's sort order, two `changed` DDP messages are sent, which I believe originates in the `DiffSequence` package on [these](https://github.com/meteor/meteor/blob/devel/packages/diff-sequence/diff.js#L182-L184) lines of code, though I could be wrong.

I'm making the argument that the change should be made atomic and if the `movedBefore` and `changed` messages sent by `AnyDb` don't conflict with each other, they could conceivably be combined into a single message. I'm proposing this because I'm using React and am getting unnecessary renders due to the data changing twice, once for its position and once for its field changes. 

@ccorcos, what do you think? Is there a way we can hack `DiffSequence` or `AnyDb` to only call `movedBefore` on the observer, but also pass in any changed fields?

**Comment by ccorcos** [comment]
Yeah, this is an issue with how DiffSequence and DDP work. They definitely ought to be combined into one. You'll probably just want to defer the re-render. Basically just subscribe to changes and then set a re-render on a setTimeout of zero. This way, any other subscription updates can happen atomically.

**Comment by ccorcos** [comment]
In blaze, Tracker takes care of this by using Meteor.defer.

**Comment by ccorcos** [comment]
Something like this:

``` js
function batched(f) {
  var timerId = null
  return function() {
    if (!timerId) {
      timerId = Meteor.defer(function() {
        timerId = null
        f()
      })
    }
  }
}
```

Then when you want to re-render.

``` js
var rerender = batched(render)

var state = null;

sub.onChange(function(value) {
  state = value
  rerender()
})

function render() {
  ReactDOM.render(<App state={state}/>, mountNode)
}
```

**Comment by sunny-g** [comment]
Would that work? I haven't gotten the time to test it just yet, but I would think that each DDP message would be handled within their own cycle of the event loop, so deferring the render would only defer the first message's render, but not long enough to call it after handling the subsequent DDP message. 

I'm also in the React Native environment, so I'd be using a `setTimeout` of 0 or a `setImmediate`, but my point, if valid, still remains.

**Comment by ccorcos** [comment]
I'd imagine that the messages would some in one after another.

This is actually wrong, you'd want to keep deferring if the next tick also calls re-render.

``` js
function batched(f) {
  var timerId = null
  return function() {
    clearTimeout(timerId)
    timerId = Meteor.defer(function() {
      timerId = null
      f()
    })
  }
}
```

but I'm pretty sure this should work.
