### ISSUE TITLE
Request for example application

### ISSUE THREAD

**Issue by pram** [ccorcos/meteor-any-db#7]
Could you create a small example application similar to the [any-db example](https://github.com/samcorcos/anydb-example)

**Comment by ccorcos** [comment]
well theres this example: https://github.com/ccorcos/meteor-any-db#api

**Comment by schabluk** [comment]
Hi, do you have any examples how to use AnyDB with React in Meteor? From [this](https://github.com/meteor/react-packages/issues/80) topic I know you don't use ReactMeteorData mixin.

**Comment by ccorcos** [comment]
this series of artiles: https://medium.com/@chetcorcos/shindig-react-data-component-aa0d2c82059e#.vs4dc2l4k

**Comment by schabluk** [comment]
Ah, how could I missed that one! Thank you.

**Comment by Looltech** [comment]
@ccorcos Please update example.
I found function like `DB.createSubscription` not work anymore.
