### ISSUE TITLE
Setup with AWS DynamoDB

### ISSUE THREAD

**Issue by Looltech** [ccorcos/meteor-any-db#8]
Does any setup with AWS DynamoDB when using any-db ?

**Comment by ccorcos** [comment]
AnyDb is database agnostic. So long as you can make requests in node anydb will work

**Comment by Looltech** [comment]
Hi team,

Please help me figure out this error in console:

``` javascript
TypeError: undefined is not an object (evaluating 'sub.addedBefore')
```

# pub

``` javascript
AnyDb.publish 'Owners', ->
  Owners.find().fetch()
```

# sub

``` javascript
sub = AnyDb.subscribe 'Owners'
```

# Data

``` javascript
data = sub.data
```

And I cannot display data as list

**Comment by ccorcos** [comment]
```
sub = AnyDb.subscribe 'Owners', {}
```

you need to have args

**Comment by ccorcos** [comment]
you'll also want to use the onReady callback function
